baseURL = "https://blog.depixapp.com/"
title = "DePix App Blog"
defaultContentLanguage = "pt"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
  [markup.highlight]
    style = "monokai"
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[languages]
  [languages.pt]
    languageName = "Portugues"
    weight = 1
    #contentDir = "content/pt"
    [languages.pt.params]
      description = "Tudo sobre o DePix: Aprenda a usar a melhor ferramenta de privacidade financeira no Brasil"
      cta = "Comece a usar o DePix App"
      langLabel = "PT"
      otherLangLabel = "EN"

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"
    [languages.en.params]
      description = "All about DePix: Learn how to use the best financial privacy tool in Brazil"
      cta = "Start using DePix App"
      langLabel = "EN"
      otherLangLabel = "PT"

[params]
  author = "DePix"
  appUrl = "https://depixapp.com/"
  logo = "/icon-192.png"
  ogImage = "/icon-512.png"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[sitemap]
  changefreq = "weekly"
  priority = 0.8
